### Add a new post
POST http://localhost:3000/post/
Content-Type: application/json

{
    "message": "Bake post.",
    "sender": "456"
}
###
### Get all posts 
GET http://localhost:3000/post/ 
###
### Get a post by id
GET http://localhost:3000/post/673a12dc4c23bab6e22b6ab2
###

### Get posts by sender
GET http://localhost:3000/post/sender/123456
###

### Update a post by id
PUT http://localhost:3000/post/673a15cb5c1f38117915432f
Content-Type: application/json

{
"message": "This is egg post.",
"sender": "123456"
}