### Add a new post
POST http://localhost:3000/post/
Content-Type: application/json

{
    "message": "Cake post.",
    "sender": "159"
}
###
### Get all posts 
GET http://localhost:3000/post/ 
###
### Get a post by id
GET http://localhost:3000/post/673a12dc4c23bab6e22b6ab2
###

### Get posts by sender
GET http://localhost:3000/post/sender/123456
###

### Update a post by id
PUT http://localhost:3000/post/673a15cb5c1f38117915432f
Content-Type: application/json

{
"message": "This is egg post.",
"sender": "123456"
}
###

//-------- COMMENT API'S-------
### Create comment
POST http://localhost:3000/comment/
Content-Type: application/json

{
  "message": "Looks good",
  "sender": "565",
  "post": "673a15cb5c1f38117915432f"
}
###

### Get all comments
GET http://localhost:3000/comment/
###

### Get comment by ID
GET http://localhost:3000/comment/673f5189959990f0269d484e
###

### Get comment by post ID
GET http://localhost:3000/comment/post/673a12dc4c23bab6e22b6ab2
###

### Update comment
PUT  http://localhost:3000/comment/673f5189959990f0269d484e
Content-Type: application/json

{
  "message": "Sounds awesome",
  "sender": "1234"
}
###
### Delete comment
DELETE http://localhost:3000/comment/673f85aabe1a37447fdc7d1a
###